AllCops:
  TargetRubyVersion: 2.6

# Layout
Layout:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

# Metrics
Metrics:
  Enabled: false

# Style
Style:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
